### ISSUE TITLE
Message printing functions

### ISSUE THREAD

**Issue by renkun-ken** [ManuelHentschel/vscDebugger#11]
Currently, we could overwrite `cat` and `print` so that calling these two functions will send the output to vscode.

However, there are many other ways and use cases that could generate output to either stdout or stderr. Following is a list I could think of:

```r
cat("hello", file = stdout())
cat("hello", file = stderr())
writeLines("hello", file = stdout())
writeLines("hello", file = stderr())
print.default("hello")
warning("hello") # to stderr
message("hello") # to stderr
stop("hello") # to stderr
```

Is there anything we could do about those?

**Comment by ManuelHentschel** [comment]
Regarding calls that explicitly specify a file (`cat(..., file=XXX)`, `writeLines(..., file=XXX)` and `print(..., file=XXX)`): I think we should pass those through to `base::cat` etc.. Otherwise we might break scripts that intend to write to an actual file instead of stdio.

I've personally never used `print.default()`. In what scenarios would this function be used over `print()`?

Having `warning`, `message`, and `stop` show the file and line number would be nice to have, but I'm a bit worried about breaking the internal mechanics behind those (stuff like `suppressWarnings`, `warnings()`, `options(warn=...)`, error-handling for `stop()` etc.)

**Comment by renkun-ken** [comment]
You are right, my point is that there are millions of ways to write something out.

A major use case of specialized S3 methods (e.g. `print.default()`) is to reduce the method dispatch overhead which could be significant when it is called millions of times in a loop. But `print.default()` is probably not a good case for this purpose since printing millions of lines of output does not look good in R anyway.

In debug mode, user might be particularly interested in output to stderr, which could be the very reason to start a debugging.

**Comment by ManuelHentschel** [comment]
The output of `stdout` and `stderr` is already captured by the VS Code extension and printed to the debug console, if it does not match any of the regexes used to parse data meant for the debugger (`<v\s\c>...</v\s\c>`) or info from the `browser()` (e.g. `Browse[1]> ` or `Called from: ...`).
Hence (if everething works), no information printed by the program is "lost", but so far the source info is only added for plain calls to `cat` and `print`.

If we manage to add the source info to other forms of output as well, we should go for it, but only if this does not change the behaviour/side-effects of the output function (or maybe have it disabled by default).

**Comment by renkun-ken** [comment]
Thanks for your detailed explanation!

I just tried with latest `develop` and writing to `stdout()` just works nicely. However, when I write anything to `stderr()`, the following error message appears in the debug console:

For example,

```r
foo <- function(x, y) {
  writeLines(c("hello", "world"), stderr())
  print(x)
  print(y)
  browser()
  x + y
}
```

```
object 'fullPath' not foundobject 'fullPath' not foundobject 'fullPath' not foundobject 'fullPath' not foundobject 'fullPath' not foundobject 'fullPath' not foundhello
world
```

**Comment by ManuelHentschel** [comment]
Thanks for finding that typo!
The assignments made inside the `try()` function are actually valid outside the function as well, so this error only occurs, if the first assignment to `fullPath` in the `try()` function fails. I guess I would have never spotted that myself :D

Is `.vsc.print` now working for you? Because it looks like the error would still keep `.vsc.getFilename` from working properly...

**Comment by renkun-ken** [comment]
Yes, `.vsc.print` works for me.

Just tried some `cat()` and find the following:

* `cat("hello")` works.
* `cat("hello", file = stderr())` does not show up.
* `cat("hello\n", file = stderr())` works.

**Comment by ManuelHentschel** [comment]
That looks like the expected behaviour:
- `cat("hello")` works as intended
- `cat("hello", file = stderr())` doesn't work as intended: `.vsc.cat` captures the output to stdout (which is none) and sends it back to vsc. As a 'side effect' `hello` gets printed to stderr, but doesn't show up in vsc, since the debugger relies on parsing full lines
- `cat("hello\n", file = stderr())`: works as above but since a linebreak is written, the debugger parses the line, doesn't match it to any of the regexes and prints it to the debug console

**Comment by ManuelHentschel** [comment]
Now the output to `stderr` should be handled correctly, regardless of linebreaks.

The parsing of `stdout` still relies on complete lines. This might be a bit more complicated to improve, since the chunks in which `stdout` is read are somewhat random. Therefore it's difficult to handle e.g. `Hey Bro`, since the line might end as `Hey Bro!\n` (which would be printed), or e.g. `Hey Browser[1]> ` (of which only the `Hey ` would be printed).

To some extent this is impossible to fix with the current parsing approach, since any program might print otuput that looks identical to the output from `browser()`. It should be possible to print the `Hey ` part from the example above immediately, since it cannot match any string that is hidden. But figuring this out is a bit more difficult, so I am currently not focussing this.
