### ISSUE TITLE
Source functions

### ISSUE THREAD

**Issue by renkun-ken** [ManuelHentschel/vscDebugger#12]
Current, we could overwrite `source()` with `debugSource()` so that sourced scripts could be debugged too.

There's also a `sys.source()`. Do we want to do similar things with it too?

**Comment by ManuelHentschel** [comment]
I've personally never used `sys.source()`, but it looks quite similar to `source()`, so we could overwrite it as well.
Also we should probably make sure that `.vsc.debugSource` correctly handles all (relevant) arguments that might be passed to `source` or `sys.source`.

**Comment by ManuelHentschel** [comment]
I've had a look at `sys.source` and my impression is that people who use `sys.source()` over `source()` probably have a reason to do so. So I would rather not overwrite it in order to keep the debugger's footprint small.

In https://github.com/ManuelHentschel/vscDebugger/pull/42 I changed some of the arguments to `.vsc.debugSource` to properly handle some of the arguments that can be given to `source` or `sys.source`. Most other arguments are captured by the `...` without doing anything, but those are mostly for output formatting etc. , which we do not do anyways.

**Comment by renkun-ken** [comment]
My use case of `sys.source()` instead of `source()` is that sometimes I need to source a script in a particular environment for its side effects, which is supported by `sys.source(file, envir)`, while `source()` only supports evaluating the expressions in global environment by default or local environment.

```r
e <- new.env()
sys.source("file.R", e)
# do something with e
```

**Comment by ManuelHentschel** [comment]
Would 
``` r
e <- new.env()
source("file.R", local = e)
```
work for this usecase?

**Comment by renkun-ken** [comment]
Just forgot `source()` accepts `local = e`. Thanks for the reminder!

I'm totally okay with minimal footprint of debugger by only replacing `source()`. Just need to document this somewhere.
