### ISSUE TITLE
Error: no more error handlers available

### ISSUE THREAD

**Issue by renkun-ken** [ManuelHentschel/vscDebugger#17]
When a breakpoint is hit, when I evaluate the following expressions multiple times, an error occurs:

I got a empty output for the following:

```r
> Sys.getenv("HOME")
```

Then all calls to `Sys.getenv` result in the following error:

```r
> Sys.getenv("HOME")
Error: no more error handlers available (recursive errors?); invoking 'abort' restart
```

**Comment by ManuelHentschel** [comment]
The initial problem was in the string escaping of the VSC Extension, which was quick to fix.

The subsequent problems were caused by the fact that errors that occurr in 'our' code are not well handled. Hence, R entered the browser after the first error and then each subsequent call also caused an error (and therefore a nested call to `browser()`), which probably resulted in R running out of error handlers.

**Comment by renkun-ken** [comment]
Thanks for the quick fix!

Still one question, why we get nothing return from `Sys.getenv("HOME")` in the debug console?
