### ISSUE TITLE
Global variables and settings

### ISSUE THREAD

**Issue by ManuelHentschel** [ManuelHentschel/vscDebugger#25]
@renkun-ken  Do you have any suggestions how to properly handle global variables and settings for the R package?

So far, everything 'global' is in the `.packageEnv`, but this can be quite annoying to type out all the time. Would you rather just define those in an `aaaGlobal.R` etc.? And is it 'best practice' to define our settings via `options(...)` or in a/some custom variable(s)?

**Comment by renkun-ken** [comment]
In this package, the global variables are used to keep a global internal state, therefore they need  reference semantics when accessed, which is only provided by R environment. `options()` is most useful for user to manage global settings rather than internal states.

Therefore, we should keep using an environment to store global variables but limit its initialization in one file and avoid direct access outside functions in other places. It is almost a bare-bone class if we use a R6 class to represent its structure.

I've been working on a PR for this.
