### ISSUE TITLE
VarInfo of data frame provides only row representation

### ISSUE THREAD

**Issue by renkun-ken** [ManuelHentschel/vscDebugger#61]
Currently, the var info of a data frame has a row-wise representation, which I think could be misleading (a list of lists?). Should we respect its real structure (a list of vectors) and provide a row-wise representation in attributes (e.g. `_rows`) or something?

<img width="361" alt="image" src="https://user-images.githubusercontent.com/4662568/85147539-98a99f80-b281-11ea-8538-67d85bc8bdd6.png">

If the data frame is huge, then the row-wise representation might be problematic while the original column-wise representation works well.

**Comment by ManuelHentschel** [comment]
You can set `options(vsc.matricesByRow = FALSE)` to view matrices and data frames column-wise.

I set the default view to row-wise since usually the entries in one row correspond to one observation or "real object" (like e.g. in the `mtcars` dataset). Also the summary of a data frame "100 obs. of 2 variables" seems to suggest that the observations (=rows) are the primary "unit" inside the data.frame.

**Comment by ManuelHentschel** [comment]
The DAP offers a possibility to load large lists of variables in chunks, maybe we should look into that for large data frames.

**Comment by ManuelHentschel** [comment]
I personally find the row-wise representation of data frames most intuitive, but that is definitely up for debate.

The entire variable view is rather easy to personalize, so we could also implement a variety of view and give the user the option to choose

**Comment by renkun-ken** [comment]
I'm curious if VSCode WebView is available in debug session? If it is so, we may support view data frame in a WebView just like vscode-R does like

![image](https://user-images.githubusercontent.com/4662568/70324083-862dc280-1869-11ea-9b95-2ef51d09103a.png)

If thought the debugger should respect the original data structure of objects as much as possible and provide alternative (more intuitive) views in addition to that. User could always use debug console to operate with the object on demand.

**Comment by ManuelHentschel** [comment]
> If thought the debugger should respect the original data structure of objects as much as possible and provide alternative (more intuitive) views in addition to that. User could always use debug console to operate with the object on demand.

Makes sense. I can adjust the default settings accordingly :)

**Comment by ManuelHentschel** [comment]
> I'm curious if VSCode WebView is available in debug session? If it is so, we may support view data frame in a WebView just like vscode-R does like

I just tried that out with the `showBrowser()` function from vscode-R and it seems to work fine. This would definitely be a nice feature to have, though I'm not quite sure how to implement it cleanly. With the latest changes, pretty much all communication between vscode and R goes via requests/responses/events specified by the DAP with some modifications described in [debugProtocolModifications.ts](https://github.com/ManuelHentschel/VSCode-R-Debugger/blob/develop/src/debugProtocolModifications.ts). In order to make the code consistent and somewhat portable I would try to stick to this approach for this feature as well.

Some ideas how to implement this:
* Using existing variable requests and 'reassemble' the variables into a data frame which is then rendered as webView inside the vscode extension --> sounds rather impractical
* Adding a new 'webview request' that produces the html in R and sends the finished website. (Though we need to find a way for the user to request this webview)
* Adding a new 'json request' that sends the data.frame as json and then produce the html in the vscode extension (Again we need to find a way for the user to request this webview)
* Not implementing this in the debugger itself, but finding a good way to use the existing vscode-R feature from inside a debugged R session.
* ...?

**Comment by renkun-ken** [comment]
There's an overlap between vscode-R and R Debugger in terms of viewing variables in WebView or show plot. So I think we should leave R Debugger to only do debugging stuff and let vscode-R do such WebView things. When I test with attaching vscode-R session watcher to the debug session, it turns out that the working directory in debug session:

```
Starting R session...
rDelimiter0: <v\s\c>
rDelimiter1: </v\s\c>
rPrompt: <#v\s\c>
rContinue: <##v\s\c>
rStartup: <v\s\c\R\STARTUP>
rLibraryNotFound: <v\s\c\LIBRARY\NOT\FOUND>
rAppend:  ### <v\s\c\COMMAND>
cwd: undefined
rPath: /usr/local/bin/R
rArgs: --ess --quiet --interactive --no-save
WARNING: unknown option '--ess'
> <v\s\c\R\STARTUP>
library: vscDebugger
> >
```

If the `cwd` is correct (e.g. `{workspaceFolder}`) then vscode-R session watcher should auto attach to the interactive debug session to make View and plot all work.

**Comment by renkun-ken** [comment]
>Makes sense. I can adjust the default settings accordingly :)

Yes, it would be nice if debugger respects original data structures unless quite necessary and let vscode-R present the data structures in a nicer or more intuitive way.
