### ISSUE TITLE
Significant delay in viewing large object in a frame

### ISSUE THREAD

**Issue by renkun-ken** [ManuelHentschel/vscDebugger#77]
Suppose we debug the following `main` function:

```r
main <- function() {
  n <- 5
  res <- lapply(seq_len(n), function(i) {
    x <- rnorm(10000)
    y <- rnorm(10000)
    m <- lm.fit(cbind(1, x), y) ### set breakpoint on this line
    beta <- coef(m)
    beta
  })
  print(res)
}
```

Hover on any variable when the breakpoint it hit or expand the frame like the following, there's a significant delay (more than 10 seconds in this case)

![image](https://user-images.githubusercontent.com/4662568/86108936-60625680-baf6-11ea-9412-d0eb19afba88.png)

Looks like the elements are loaded too eagerly. I'm wondering if the elements should only be loaded when expanding the variable rather than the frame.

**Comment by ManuelHentschel** [comment]
Thanks for raising this issue!
> Looks like the elements are loaded too eagerly. I'm wondering if the elements should only be loaded when expanding the variable rather than the frame.

Yep, that seems to be the issue. Solving this will be somewhat difficult, since the entire system of displaying variable infos is not optimized for vectors/lists of that size yet. One problem with lazy loading here is that, in order to show the variables in chunks, the total number of variables needs to be known when the variable is displayed for the first time (i.e. when expanding the scope, not just when expanding the variable itself). And due to the flexible nature of the VarInfos, this is currently done by retrieving the list of child variables and checking the length.

**Comment by renkun-ken** [comment]
The latest version works nicely now. Thanks!
